apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: icgroup
  labels:
    env: prod
data:
  ODOO_URL: "http://odoo.icgroup.local"
  PGADMIN_URL: "http://pgadmin.icgroup.local"

